[package]
name = "bevy_egui"
version = "0.1.0"
authors = ["mvlabat <mvlabat@gmail.com>"]
description = "A plugin for Egui integration into Bevy"
license = "MIT"
edition = "2018"
repository = "https://github.com/mvlabat/bevy_egui"
exclude = ["assets/**/*", ".github/**/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["manage_clipboard", "open_url"]
manage_clipboard = ["clipboard"]
open_url = ["webbrowser"]

[dependencies]
bevy = { version = "0.4", default-features = false, features = ["render"] }
bevy_winit = "0.4.0"
egui = "0.7.0"
thread_local = "1.1.0"
webbrowser = { version = "0.5.5", optional = true }
winit = { version = "0.24.0", default-features = false }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
clipboard = { version = "0.5.0", optional = true }

[[example]]
name = "ui"
path = "examples/ui.rs"
required-features = ["bevy/x11", "bevy/png", "bevy/bevy_wgpu"]
